const char *g_illegal		= "ILLEGAL";
const char *g_eof			= "EOF";
const char *g_ident			= "IDENT";
const char *g_assign		= "ASSIGN";
const char *g_int			= "INT";
const char *g_plus			= "+";
const char *g_comma			= ",";
const char *g_semmicolon	= ";";
const char *g_lparen		= "(";
const char *g_rparen		= ")";
const char *g_lbrace 		= "{";
const char *g_rbrace 		= "}";
const char *g_function 		= "FUNCTION";
const char *g_let 			= "LET";
const char *g_minus 		= "-";
const char *g_bang 			= "!"
const char *g_asterik 		= "*"
const char *g_slash 		= "/"
const char *g_lt 			= "<"
const char *g_gt 			= ">"
const char *g_true 			= "true"
const char *g_false 		= "false";
const char *g_if 			= "if";
const char *g_else 			= "else";
const char *g_return 		= "return";
const char *g_eq 			= "==";
const char *g_not_eq 		= "!=";